# Generated by Django 5.2.5 on 2025-08-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenddeveloper',
            name='passkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='frontenddeveloper',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/frontend_profiles/'),
        ),
    ]
