# Generated by Django 5.2.5 on 2025-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0002_frontenddeveloper_passkey_frontenddeveloper_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenddeveloper',
            name='user',
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='bio',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='passkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='frontend_profiles/'),
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='skills',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frontenddeveloper',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
