# Generated by Django 5.2.5 on 2025-08-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0004_entry'),
        ('dear_journal_app', '0004_signupcode'),
    ]

    operations = [
    ]
