# Generated by Django 5.2.5 on 2025-09-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0005_merge_0004_entry_0004_signupcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
