# Generated by Django 5.2.5 on 2025-09-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0006_delete_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupCode',
            new_name='User',
        ),
    ]
