# Generated by Django 5.2.5 on 2025-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0007_rename_signupcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('passkey', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FrontendDeveloper',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
