# Generated by Django 5.2.5 on 2025-09-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0009_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='client',
            name='skills',
        ),
    ]
