# Generated by Django 5.2.5 on 2025-09-19 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0010_remove_client_bio_remove_client_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='dear_journal_app.client'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
    ]
