# Generated by Django 5.2.5 on 2025-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dear_journal_app', '0011_remove_journal_user_journal_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AlterField(
            model_name='client',
            name='passkey',
            field=models.CharField(default='temp123', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='temp123', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
